### ISSUE TITLE
Açıklama

### ISSUE THREAD

**Issue by nilguncanbaz** [nlgncnbzz/internetProje#1]
localhosta çalıştırmak için dosyaları server klasörüne atıp ev-gelir-gider.sql dosyasını localhostta veritabanına attıktan sonra sıkıntısız bir şekilde çalışacaktır.

**Comment by nlgncnbzz** [comment]
> localhosta çalıştırmak için dosyaları server klasörüne atıp ev-gelir-gider.sql dosyasını localhostta veritabanına attıktan sonra sıkıntısız bir şekilde çalışacaktır.
